// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iewxaqrojsrfbdzhflyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlld3hhcXJvanNyZmJkemhmbHlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNzUxNDgsImV4cCI6MjA3MTY1MTE0OH0.TzoHV7t6tHbPx21J5nwCPgnnv4jEOv3A-ViQsgigrys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});